# Listas

<span style="color: red;"><b>Todos os exercícios são feitos partindo-se do pressuposto de que todas as entradas são dadas de forma correta. Casos limite não mencionados no enunciado não são abordados porque não fazem parte do exercício.</b></span>

#### 1. Faça um Programa que leia as vendas dos vendedores, mostre a venda de cada vendedor com o seu nome e a média de vendas.

In [ ]:
vendas = [1000, 1500, 1200, 1300]
vendedores = ["Fulano", "Beltrano", "Ciclano", "Lira"]

for i, venda in enumerate(vendas):
    print(f"O vendedor {vendedores[i]} vendeu {venda}")

O vendedor Fulano vendeu 1000
O vendedor Beltrano vendeu 1500
O vendedor Ciclano vendeu 1200
O vendedor Lira vendeu 1300

#### 2. Faça um Programa que crie uma lista com as médias de cada aluno, imprima as médias de cada aluno e a quantidade de alunos com média maior que 7.

In [ ]:
alunos = ["José", "Joana", "Maria", "Carla", "Mauricio", "Andre", "Tiago", "Enzo", "Amanda", "Alessandra"]
notas = [
    [10, 9, 8, 8],
    [9, 7, 6, 4],
    [10, 10, 10, 10],
    [5, 3, 10, 9],
    [7, 6, 6, 6],
    [7, 7, 8, 7],
    [7, 7, 7, 9],
    [8, 5, 6, 7],
    [10, 9, 7, 4],
    [10, 1, 3, 3],
]


for i, aluno in enumerate(alunos):
    media = sum(notas[i]) / len(notas[i])
    print(f"O aluno {aluno} teve média {media}")

O aluno José teve média 8.75
O aluno Joana teve média 6.5
O aluno Maria teve média 10.0
O aluno Carla teve média 6.75
O aluno Mauricio teve média 6.25
O aluno Andre teve média 7.25
O aluno Tiago teve média 7.5
O aluno Enzo teve média 6.5
O aluno Amanda teve média 7.5
O aluno Alessandra teve média 4.25

#### 3. Foram anotadas as idades e salários de 30 funcionários. Faça um programa que determine quantos funcionários com mais de 25 anos possuem salário inferior à média de todos os salários.

In [ ]:
idades = [35,32,50,33,48,50,33,48,22,49,35,38,20,47,49,48,34,21,48,44,48,30,25,42,42,23,25,23,38,35]
salarios = [3739,2219,3554,3978,4014,3270,4792,3879,2981,2384,4826,2460,3680,4318,1872,1770,4640,3929,3295,1729,3965,4267,4007,1916,2987,2943,3852,4543,2055,1730]

media_salarial = sum(salarios)/len(salarios)
print(media_salarial)
funcionarios_abaixo_da_media = 0

if len(idades) == len(salarios):
    for i, idade in enumerate(idades):
        if idade > 25:
            if salarios[i] < media_salarial:
                funcionarios_abaixo_da_media += 1


print(funcionarios_abaixo_da_media)

3319.8
12

#### 4.Em quais meses a média de temperatura foi maior do que a média nacional?

In [ ]:
meses = [
    'Janeiro',
    'Fevereiro',
    'Março',
    'Abril',
    'Maio',
    'Junho',
    'Julho',
    'Agosto',
    'Setembro',
    'Outubro',
    'Novembro',
    'Dezembro'
]

temperaturas = [30, 29, 28, 28, 25, 26, 20, 21, 19, 25, 27, 32]

media_temperaturas = sum(temperaturas)/len(temperaturas)
print(media_temperaturas)

for i,mes in enumerate(meses):
    print(f'O mês {mes.capitalize()} teve temperaturas mais altas que a média anual.') if temperaturas[i] > media_temperaturas else None

25.833333333333332
O mês Janeiro teve temperaturas mais altas que a média anual.
O mês Fevereiro teve temperaturas mais altas que a média anual.
O mês Março teve temperaturas mais altas que a média anual.
O mês Abril teve temperaturas mais altas que a média anual.
O mês Junho teve temperaturas mais altas que a média anual.
O mês Novembro teve temperaturas mais altas que a média anual.
O mês Dezembro teve temperaturas mais altas que a média anual.

#### 5. As Organizações Tabajara resolveram dar um abono aos seus colaboradores em reconhecimento ao bom resultado alcançado durante o ano que passou. Para isto contratou você para desenvolver a aplicação que servirá como uma projeção de quanto será gasto com o pagamento deste abono.
<pre>Após reuniões envolvendo a diretoria executiva, a diretoria financeira e os representantes do sindicato laboral, chegou-se a seguinte forma de cálculo:
. Cada funcionário receberá o equivalente a 20% do seu salário bruto de dezembro;
. O piso do abono será de 100 reais, isto é, aqueles funcionários cujo salário for muito baixo, recebem este valor mínimo;

Neste momento, não se deve ter nenhuma preocupação com colaboradores com tempo menor de casa, descontos, impostos ou outras particularidades. O programa deverá calcular o valor do abono concedido a cada colaborador, de acordo com a regra definida acima. Ao final, o programa deverá apresentar:</pre>
<pre>
O salário de cada funcionário, juntamente com o valor do abono;
O número total de funcionário processados;
O valor total a ser gasto com o pagamento do abono;
O número de funcionário que receberá o valor mínimo de 100 reais;
O maior valor pago como abono; A tela abaixo é um exemplo de execução do programa, apenas para fins ilustrativos.
<pre>
Projeção de Gastos com Abono
============================

Salário: 1000
Salário: 300
Salário: 500
Salário: 100
Salário: 4500
Salário: 0

Salário    - Abono     
R$ 1000.00 - R$  200.00
R$  300.00 - R$  100.00
R$  500.00 - R$  100.00
R$  100.00 - R$  100.00
R$ 4500.00 - R$  900.00

Foram processados 5 colaboradores
Total gasto com abonos: R$ 1400.00
Valor mínimo pago a 3 colaboradores
Maior valor de abono pago: R$ 900.00

In [ ]:
lista_salarios = [1000, 300, 500, 200, 1500, 3000, 3400, 5000, 7000, 2000, 600, 800, 250, 1500, 20000]
abonos = []
MINIMO_ABONO = 100
funcionarios_valor_minimo = 0
funcionarios_contados = 0

print("Projeção de Gastos com Abono")
print('\n')
print("= = " * 50)
print('\n')


for salario in lista_salarios:
    if salario*0.2 < MINIMO_ABONO:
        print(f"Salario: {salario}")
        abonos.append(MINIMO_ABONO)
        funcionarios_valor_minimo += 1
        funcionarios_contados += 1

    else:
        print(f"Salario: {salario}")
        abonos.append(int(salario*0.2))
        funcionarios_contados += 1

print('\n')
print("= = " * 50)
print('\n')


print(f'Salario  -- Abono')
print('\n')

for i, salario in enumerate(lista_salarios):
        print(f'R$ {salario} - R$ {abonos[i]}')


print('\n')
print("= = " * 50)
print('\n')

print(f'Foram processados {funcionarios_contados} colaboradores')
print(f'Total gasto com abonos: R$ {sum(abonos)}')
print(f'Valor mínimo pago a {funcionarios_valor_minimo} colaboradores')
print(f'Maior valor de abono pago: R$ {max(abonos)}')

Projeção de Gastos com Abono


= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


Salario: 1000
Salario: 300
Salario: 500
Salario: 200
Salario: 1500
Salario: 3000
Salario: 3400
Salario: 5000
Salario: 7000
Salario: 2000
Salario: 600
Salario: 800
Salario: 250
Salario: 1500
Salario: 20000


= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


Salario  -- Abono


R$ 1000 - R$ 200
R$ 300 - R$ 100
R$ 500 - R$ 100
R$ 200 - R$ 100
R$ 1500 - R$ 300
R$ 3000 - R$ 600
R$ 3400 - R$ 680
R$ 5000 - R$ 1000
R$ 7000 - R$ 1400
R$ 2000 - R$ 400
R$ 600 - R$ 120
R$ 800 - R$ 160
R$ 250 - R$ 100
R$ 1500 - R$ 300
R$ 20000 - R$ 4000


= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


Foram processados 15 colaboradores
Total gasto com abonos: R$ 9560
Valor mínimo pago a 3 colaboradores
Maior valor de abono pago: R$ 4000

#### 6. Faça um programa que carregue uma lista com os modelos de cinco carros (exemplo de modelos: FUSCA, GOL, VECTRA etc). Carregue uma outra lista com o consumo desses carros, isto é, quantos quilômetros cada um desses carros faz com um litro de combustível. Calcule e mostre:
<pre>
a. O modelo do carro mais econômico;
b. Quantos litros de combustível cada um dos carros cadastrados consome para percorrer uma distância de 1000 quilômetros e quanto isto custará, considerando um que a gasolina custe R$ 2,25 o litro. Abaixo segue uma tela de exemplo. O disposição das informações deve ser o mais próxima possível ao exemplo. Os dados são fictícios e podem mudar a cada execução do programa.</pre>
```
Comparativo de Consumo de Combustível

Veículo 1
Nome: fusca
Km por litro: 7
Veículo 2
Nome: gol
Km por litro: 10
Veículo 3
Nome: uno
Km por litro: 12.5
Veículo 4
Nome: Vectra
Km por litro: 9
Veículo 5
Nome: Peugeout
Km por litro: 14.5

Relatório Final
 1 - fusca           -    7.0 -  142.9 litros - R$ 321.43
 2 - gol             -   10.0 -  100.0 litros - R$ 225.00
 3 - uno             -   12.5 -   80.0 litros - R$ 180.00
 4 - vectra          -    9.0 -  111.1 litros - R$ 250.00
 5 - peugeout        -   14.5 -   69.0 litros - R$ 155.17
O menor consumo é do peugeout.
```

In [ ]:
print('Comparativo de Consumo de Combustível')
print('\n')
print("= =" * 50)
print('\n')

veiculos = ['fusca',' gol', 'uno', 'vectra', 'peugeot']
autonomias = [7, 10, 12.5, 9, 14.5]
consumo_valor = []


for carro in veiculos:
    print(f'Veículo {veiculos.index(carro)+1}')
    print(f'Nome: {carro.capitalize()}')
    print(f'Km por litro: {autonomias[veiculos.index(carro)]}')
    print('\n')


print('\n')
print("= =" * 50)
print('\n')
print('Relatório Final')
print('\n')
print("= =" * 50)
print('\n')


for i,carro in enumerate(veiculos):
    consumo = 1000/autonomias[i]
    calculo_consulmo = consumo * 2.25
    consumo_valor.append(calculo_consulmo)
    print(f'  {i+1} - {carro.capitalize()} - {autonomias[i]} - {consumo} litros - R$ {calculo_consulmo}')
    print('\n')

print(f'O menor consumo é do {veiculos[consumo_valor.index(min(consumo_valor))].capitalize()}')

Comparativo de Consumo de Combustível


= == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == =


Veículo 1
Nome: Fusca
Km por litro: 7


Veículo 2
Nome:  gol
Km por litro: 10


Veículo 3
Nome: Uno
Km por litro: 12.5


Veículo 4
Nome: Vectra
Km por litro: 9


Veículo 5
Nome: Peugeot
Km por litro: 14.5




= == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == =


Relatório Final


= == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == =


  1 - Fusca - 7 - 142.85714285714286 litros - R$ 321.42857142857144


  2 -  gol - 10 - 100.0 litros - R$ 225.0


  3 - Uno - 12.5 - 80.0 litros - R$ 180.0


  4 - Vectra - 9 - 111.11111111111111 litros - R$ 250.0


  5 - Peugeot - 14.5 - 68.96551724137932 litros - R$ 155.17241379310346


O menor consumo é do Peugeot

#### 7. Uma empresa paga seus vendedores com base em comissões. O vendedor recebe \\$200 por semana mais 9 por cento de suas vendas brutas daquela semana. Por exemplo, um vendedor que teve vendas brutas de \\$3000 em uma semana recebe \\$200 mais 9 por cento de \\$3000, ou seja, um total de \\$470. Escreva um programa (usando um array de contadores) que determine quantos vendedores receberam salários nos seguintes intervalos de valores:
<pre>
$200 - $299
$300 - $399
$400 - $499
$500 - $599
$600 - $699
$700 - $799
$800 - $899
$900 - $999
$1000 em diante
</pre>

Existem várias formas de fazer. Faça primeiro da forma que parecer mais intuitiva para você.

Em seguida, caso queira um desafio:
Desafio: Crie uma forma para chegar na posição da lista a partir do salário, sem fazer vários ifs aninhados.

In [3]:
vendas = [1000, 2000, 3000, 4000, 5000, 6000, 5500, 4500, 3600]
contadores = [0] * 9
salarios = []
faixas = ['R$200 - R$299', 'R$300 - R$399', 'R$400 - R$499', 'R$500 - R$599', 'R$600 - R$699', 'R$700 - R$799', 'R$800 - R$899', 'R$900 - R$999', 'R$1000 em diante']

for venda in vendas:
    salario = 200 + (venda * 0.09)
    salarios.append(salario)
    indice = (int(salario) - 200) // 100
    if 0 <= indice < len(contadores):
        contadores[indice] += 1


print(f'Salario  -- Contador')
print('\n')
for i, contador in enumerate(contadores):
    print(f'{faixas[i]} - Temos {contador} funcionários com essa faixa de salário.')

Salario  -- Contador


R$200 - R$299 - Temos 1 funcionários com essa faixa de salário.
R$300 - R$399 - Temos 1 funcionários com essa faixa de salário.
R$400 - R$499 - Temos 1 funcionários com essa faixa de salário.
R$500 - R$599 - Temos 2 funcionários com essa faixa de salário.
R$600 - R$699 - Temos 3 funcionários com essa faixa de salário.
R$700 - R$799 - Temos 1 funcionários com essa faixa de salário.
R$800 - R$899 - Temos 0 funcionários com essa faixa de salário.
R$900 - R$999 - Temos 0 funcionários com essa faixa de salário.
R$1000 em diante - Temos 0 funcionários com essa faixa de salário.